import type { Job } from './types';

export const sampleJobs: Job[] = [
  {
    id: '1',
    title: 'Assistant Professor - Computer Science',
    department: 'Department of Computer Science',
    institution: 'Stanford University',
    location: 'Stanford, CA',
    jobType: 'Full-time',
    field: 'Computer Science',
    description: 'We are seeking talented researchers for tenure-track positions in all areas of computer science. Strong commitment to teaching and research excellence required.',
    salary: '120,000 - 150,000',
    deadline: '2026-06-30',
  },
  {
    id: '2',
    title: 'Postdoctoral Fellow - Biomolecular Science',
    department: 'Department of Biology',
    institution: 'Massachusetts Institute of Technology',
    location: 'Cambridge, MA',
    jobType: 'Postdoc',
    field: 'Biology',
    description: 'Seeking exceptional postdoc to join our research group studying protein structures and cellular mechanisms.',
    salary: '65,000 - 75,000',
    deadline: '2026-05-31',
  },
  {
    id: '3',
    title: 'Lecturer - Physics',
    department: 'Department of Physics',
    institution: 'University of Oxford',
    location: 'Oxford, UK',
    jobType: 'Full-time',
    field: 'Physics',
    description: 'Fixed-term lectureship in theoretical physics. Teaching and research responsibilities in quantum mechanics and related fields.',
    salary: '50,000 - 65,000',
    deadline: '2026-06-15',
  },
  {
    id: '4',
    title: 'Research Scientist - Machine Learning',
    department: 'AI Research Lab',
    institution: 'University of California, Berkeley',
    location: 'Berkeley, CA',
    jobType: 'Full-time',
    field: 'Computer Science',
    description: 'Lead research initiatives in cutting-edge machine learning. Develop novel algorithms and mentor graduate students.',
    salary: '140,000 - 180,000',
    deadline: '2026-07-31',
  },
  {
    id: '5',
    title: 'Teaching Assistant - Chemistry',
    department: 'Department of Chemistry',
    institution: 'Yale University',
    location: 'New Haven, CT',
    jobType: 'Part-time',
    field: 'Chemistry',
    description: 'Support undergraduate laboratory courses. Previous experience in general chemistry preferred.',
    salary: '18 - 22/hour',
    deadline: '2026-08-30',
  },
  {
    id: '6',
    title: 'Senior Researcher - Economics',
    department: 'Institute for Economic Policy',
    institution: 'Harvard University',
    location: 'Cambridge, MA',
    jobType: 'Full-time',
    field: 'Economics',
    description: 'Conduct research on economic policy and development. Present findings at conferences and publish in peer-reviewed journals.',
    salary: '100,000 - 130,000',
    deadline: '2026-06-20',
  },
  {
    id: '7',
    title: 'Adjunct Professor - English Literature',
    department: 'Department of English',
    institution: 'University of Washington',
    location: 'Seattle, WA',
    jobType: 'Part-time',
    field: 'Humanities',
    description: 'Teach courses in contemporary literature and literary criticism. Master\'s degree required.',
    salary: '40,000 (per course)',
    deadline: '2026-07-10',
  },
  {
    id: '8',
    title: 'Research Affiliate - Environmental Science',
    department: 'Environmental Research Center',
    institution: 'University of Cambridge',
    location: 'Cambridge, UK',
    jobType: 'Contract',
    field: 'Environmental Science',
    description: 'Join our interdisciplinary team studying climate change impacts and sustainable solutions.',
    salary: '55,000 - 75,000',
    deadline: '2026-08-15',
  },
];
